name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
         submodules: 'true' 

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libcmocka-dev
    
    - name: Build
      run: |
        make -C deps/mulib/
        CC=gcc make
    - name: Tests
      run: |
        make test
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
